### ISSUE TITLE
Custom path options for asset path prefix

### ISSUE THREAD

**Issue by nabi-chan** [remcohaszing/remark-mdx-images#7]
## What's up?
I'm using this package nextJS with mdx-bundler,
However, when I set image on `/posts/{post_id}/0.png` This library always throws 'Could not resolve ...' Error

More clearly, I'll make a situation.

### File Tree
```
└── posts
    ├── target
    │   └── test.png
    └── test.mdx
```

### Markdown File (test.mdx)
```mdx
![This image will be shown](./target/test.png)
```

## Expect result
Showing image

## Current result
Error :  Could not resolve "./target/test.png"

## How can fix this issue?

I think We can gave option about start path of assets (e.g: `assetPrefix`)
When I set `assetsPrefix` to `./posts`, file path will be `./posts/target/test.png`.

**Comment by remcohaszing** [comment]
This appears to be a problem with how paths are resolved in your project, not how this plugin transforms the AST.

This plugin takes your input:

```md
![This image will be shown](./target/test.png)
```

and transforms it into the following MDX

```mdx
import targetTestImage from './target/test.png'

<img alt="" src={targetTestImage} title="This image will be shown" />
```

This works exactly as expected, also for your situation. The solution you proposed will bite you, because it resolved the situation for this exact import, but not for any other imports in your file. I.e. you could have something like this:

```mdx
import { Button } from '../components/Button.js'

![This image will be shown](./target/test.png)

<Button />
```

Now this plugin with you proposal would transform it into the following, which leads to much harder to resolve issues:

```mdx
import targetTestImage from './posts/target/test.png'
import { Button } from '../components/Button.js'

<img alt="" src={targetTestImage} title="This image will be shown" />

<Button />
```

A proper solution to your problem would be to fix the way imports are resolved. I’m not familiar with `mdx-bundler`, so I can’t help with that.
